name: import_sorter
description: Automatically organize your dart imports
version: 4.6.0
repository: "https://github.com/fluttercommunity/import_sorter"
homepage: "https://mattglei.ch"
maintainer: Matthew Gleich (@gleich)

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.0
  tint: ^2.0.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.7


import_sorter:
  emojis: true
